export const trips:{
    name: string,
    country: string,
    start_date: Date,
    end_date: Date,
    price: number,
    capacity: number,
    description: string,
    rate: number,
    img_link: string}[] = [
{
    name: "Fajna wycieczka",
    country: "Polska",
    start_date: new Date(2021,1,1),
    end_date: new Date(2021,1,15),
    price: 8500,
    capacity: 5,
    description: "Polska fajna jest ale nie tak fajna jak Kraków",
    rate: -1,
    img_link: '../assets/miasto3.jpg'
    },
    {
    name: "Fajna wycieczka",
    country: "Austria",
    start_date: new Date(2021,1,1),
    end_date: new Date(2021,1,15),
    price: 7500,
    capacity: 5,
    description: "Polska fajna jest",
    rate: -1,
    img_link: '../assets/miasto3.jpg'
    },
    {name: "Fajna wycieczka",
    country: "Węgry",
    start_date: new Date(2021,1,1),
    end_date: new Date(2021,1,15),
    price: 1500,
    capacity: 5,
    description: "Polska fajna jest ale nie tak fajna jak Kraków",
    rate: -1,
    img_link: '../assets/miasto3.jpg'
    },
    {
    name: "Fajna wycieczka",
    country: "Niemcy",
    start_date: new Date(2021,1,1),
    end_date: new Date(2021,1,15),
    price: 2500,
    capacity: 5,
    description: "Polska fajna jest ale nie tak fajna jak Kraków",
    rate: -1,
    img_link: '../assets/miasto3.jpg'
    },
    {name: "Fajna wycieczka",
    country: "Polska",
    start_date: new Date(2021,1,1),
    end_date: new Date(2021,1,15),
    price: 3500,
    capacity: 5,
    description: "Polska fajna jest ale nie tak fajna jak Kraków",
    rate: -1,
    img_link: '../assets/miasto3.jpg'
    },
    {name: "Fajna wycieczka",
    country: "Polska",
    start_date: new Date(2021,1,1),
    end_date: new Date(2021,1,15),
    price: 4500,
    capacity: 5,
    description: "Polska fajna jest ale nie tak fajna jak Kraków",
    rate: -1,
    img_link: '../assets/miasto3.jpg'
    },
    {name: "Fajna wycieczka",
    country: "Polska",
    start_date: new Date(2021,1,1),
    end_date: new Date(2021,1,15),
    price: 5500,
    capacity: 5,
    description: "Polska fajna jest ale nie tak fajna jak Kraków",
    rate: -1,
    img_link: '../assets/miasto3.jpg'
    },
    {name: "Fajna wycieczka",
    country: "Polska",
    start_date: new Date(2021,1,1),
    end_date: new Date(2021,1,15),
    price: 6500,
    capacity: 5,
    description: "Polska fajna jest ale nie tak fajna jak Kraków",
    rate: -1,
    img_link: '../assets/miasto3.jpg'
    }
];